image:
  - Visual Studio 2017

build_script:
  - cmd: mkdir batch_file_renamer_cmake
  - cmd: cd batch_file_renamer_cmake
  - cmd: cmake -G "Visual Studio 15 2017 Win64" ../
  - cmd: cmake --build . --config Release
