image:
  - Visual Studio 2013

install:
  - cmd: choco install conan
  - cmd: choco install nuget.commandline
  - cmd: refreshenv

build_script:
  - cmd: mkdir batch_file_renamer_cmake
  - cmd: cd batch_file_renamer_cmake
  - cmd: cmake -G "Visual Studio 12 2013 Win64" ..\
  - cmd: cmake --build . --config Release

test_script:
  - cmd: ctest --build-config Release --verbose
