image:
  - Visual Studio 2013

cache:
  - '%USERPROFILE%\.conan\data -> CMakeLists.txt'

install:
  - cmd: choco install conan
  - cmd: refreshenv
  - cmd: conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  - cmd: choco install nuget.commandline

build_script:
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake -G "Visual Studio 12 2013 Win64" ..\
  - cmd: cmake --build . --config Release

test_script:
  - cmd: ctest --build-config Release --verbose

artifacts:
  - path: build\bin\Release\
    name: batch_file_renamer
