image:
  - Visual Studio 2017

install:
  - cmd: set PATH=%PATH%;%PYTHON%/Scripts/
  - cmd: pip.exe install conan
#  - cmd: conan user # Create the conan data directory
  - cmd: conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan

build_script:
  - cmd: mkdir batch_file_renamer_cmake
  - cmd: cd batch_file_renamer_cmake
  - cmd: cmake -G "Visual Studio 15 2017 Win64" ../
  - cmd: cmake --build . --config Release
